language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install beautifulsoup4 nose coverage"
# command to run tests
script: nosetests
